### ISSUE TITLE
This project cannot be built. It seems that some necessary dependencies are missing.

### ISSUE THREAD

**Issue by WenElevating** [BluDay/impart-app-windows#1]
I am interested in this project. When I pulled the project, the compilation generated the following error:
![image](https://github.com/user-attachments/assets/690f7cae-325e-4915-a36e-a949ea5ee5fa)
I can't figure out which package these classes belong to.

**Comment by BluDay** [comment]
Hello!

You need to clone the repo of [`BluDay.Net`](https://github.com/BluDay/bluday-dotnet) to the same path containing the project, and build the assembly manually using the default `Debug` configuration. I am going to upload the package to NuGet soon.

Example directory:

* `C:\Code\`
  - `bluday-dotnet\`
  - `impart-app-windows\`

Note that the chat backend has not been written yet. I am currently working on setting up a proper infrastructure for the app core and the WinUI 3 and WPF clients.

**Comment by WenElevating** [comment]
> 你好！
> 
> 您需要将 repo 克隆[`BluDay.Net`](https://github.com/BluDay/bluday-dotnet)到包含项目的同一路径，然后使用默认`Debug`配置手动构建程序集。我很快就会将包上传到 NuGet。
> 
> 示例目录：
> 
> * `C:\Code\`
>   
>   * `bluday-dotnet\`
>   * `impart-app-windows\`
> 
> 请注意，聊天后端尚未编写。我目前正在为应用程序核心以及 WinUI 3 和 WPF 客户端设置适当的基础架构。

Hello!
Thank you very much! When adding BluDay.Net dependency, I found the lack of WinUI3 runtime environment, which finally solved the problem. If you have completed the application core and set up the appropriate infrastructure for WinUI 3 and WPF client, can I participate in the development of this project? I will first familiarize myself with the current code. Here is a screenshot of my successful run:
![image](https://github.com/user-attachments/assets/224383c1-16ef-458e-a88b-9b202ecc72d2)

**Comment by BluDay** [comment]
Nice!

Did you change the font family for all of the `FontIcon` controls? You seem to be using the old _Segoe MDL2 Assets_ font instead of the new _Segoe Fluent Icons_ font.

I will notify you once I have set up the frontend stuff. 👍

Also note that the initial C-based backend will run in the background as a separate process. I am doing it merely for an experimental reason.

* A separate C-based process (IPC) (Initial)
* A built-in .NET assembly (Non-IPC)
  - `BluDay.Impart.App`
    - `BluDay.Impart.App.Core` (Frontend)
  - `BluDay.Impart.App.WinUI3`
  - `BluDay.Impart.App.WPF`
  - `BluDay.Impart.Core` (Backend)
* A separate Rust-based process (IPC) (Maybe)

**Comment by BluDay** [comment]
Yes. The current backend is C-based. But I will make one with .NET once I get the current one to work.
